[package]
name = "mud-net"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
flate2 = "1.0"
rustls = "0.23"
rustls-pemfile = "2"
tokio = { version = "1.52.1", features = ["net", "io-util", "sync", "rt", "macros"] }
tokio-rustls = "0.26"
tracing = "0.1.44"

[lints]
workspace = true
