[package]
name = "mud-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bcrypt = "0.19.0"
bevy_ecs = "0.18.1"
chrono = "0.4.44"
dotenvy = "0.15.7"
mud-db = { version = "0.1.0", path = "../mud-db" }
mud-net = { version = "0.1.0", path = "../mud-net" }
mud-script = { version = "0.1.0", path = "../mud-script" }
mud-world = { version = "0.1.0", path = "../mud-world" }
rand = "0.10.1"
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "time", "signal"] }
rustls = "0.23"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "registry"] }

[lints]
workspace = true
