[package]
name = "mud-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bevy_ecs = "0.18.1"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "time", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true
