[package]
name = "mud-db"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono", "json"] }
thiserror = "2.0.18"

[lints]
workspace = true

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
